version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing Terraform
      - wget https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip terraform_1.3.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform --version
  build:
    commands:
      - echo Build started on `date`
      - terraform init
      - "terraform plan -out tfapply"
artifacts:
  files:
    - '**/*'
